In [1]:
import numpy as np

In [21]:
arr = np.array([3, 5, 4, 2, 6, 8, 9, 7])

In [6]:
print(np.mean(arr))

5.5


In [7]:
print(np.max(arr))

9


In [8]:
print(np.min(arr))

2


In [9]:
print(np.std(arr))

2.29128784747792


In [10]:
print(np.var(arr))

5.25


In [11]:
print(np.sum(arr))

44


In [12]:
print(np.prod(arr))

362880


In [15]:
print(np.percentile(arr, 50))

5.0


In [16]:
print(np.median(arr))

5.0


In [17]:
print(np.argmin(arr))

3


In [18]:
print(np.argmax(arr))

6


In [22]:
arr2 = np.array([2, 4, 6, 8, 9, 7, 5, 4])

In [24]:
print(np.corrcoef(arr, arr2))

[[1.         0.03760887]
 [0.03760887 1.        ]]


In [25]:
np.corrcoef(arr, arr2)

array([[1.        , 0.03760887],
       [0.03760887, 1.        ]])

In [26]:
print(np.unique(arr))

[2 3 4 5 6 7 8 9]


In [27]:
print(np.diff(arr))

[ 2 -1 -2  4  2  1 -2]


In [29]:
print(np.cumsum(arr))

[ 3  8 12 14 20 28 37 44]


In [32]:
arr3 = np.linspace(0, 10, 5)

In [33]:
arr3

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.linspace(0, 10, 5,)

array([ 0,  2,  5,  7, 10], dtype=int32)

In [37]:
print(np.log(arr))

[1.09861229 1.60943791 1.38629436 0.69314718 1.79175947 2.07944154
 2.19722458 1.94591015]


In [39]:
print(np.exp(arr))

[2.00855369e+01 1.48413159e+02 5.45981500e+01 7.38905610e+00
 4.03428793e+02 2.98095799e+03 8.10308393e+03 1.09663316e+03]
