In [2]:
import numpy as np
import time

size = 1_000_000

l1 = list(range(size)) # 99_999_99

start = time.time()

result = [x ** 2 for x in l1]

end = time.time()

end-start

0.10659384727478027

In [2]:
import numpy as np
import time

size = 1_000_000_0

l1 = np.array(list(range(size)))


start = time.time()

result = l1 ** 2

end = time.time()

end-start

0.06328415870666504

In [13]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
type(arr)

numpy.ndarray

In [25]:
arr.shape

(3, 3)

In [30]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, ])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [3, 6, 9]])
myarr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 6, 9]])

In [14]:
myarr.shape


(4, 3)

In [15]:
myarr.size


12

In [16]:
myarr.ndim

2

In [17]:
myarr.dtype

dtype('int64')

In [18]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [3, 6, 9]])

In [31]:
reshaped = myarr.reshape((2, 6))

In [32]:
reshaped

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 3, 6, 9]])

In [35]:
myarr2 = myarr.flatten()

In [36]:
myarr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 6, 9])

In [48]:
b = myarr2[2:7].copy()

In [49]:
b

array([3, 4, 5, 6, 7])

In [50]:
b[0] = 33333333
b

array([33333333,        4,        5,        6,        7])

In [51]:
myarr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 6, 9])

In [52]:
myarr2[myarr2>5]

array([6, 7, 8, 9, 6, 9])

In [53]:
myarr2[myarr2>8]

array([9, 9])

In [54]:
arr2 = np.random.rand(3, 3)

In [55]:
arr2

array([[0.82594551, 0.06511005, 0.97024427],
       [0.19090098, 0.087634  , 0.48631872],
       [0.49044115, 0.62159372, 0.28797109]])

In [56]:
int_arr = arr2.astype(int)

In [57]:
int_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
arr2[[0, 2]]

array([[0.82594551, 0.06511005, 0.97024427],
       [0.49044115, 0.62159372, 0.28797109]])

In [64]:
arr = np.array([43, 65, 78, 23, 45, 64, 34, 24, 54])

In [67]:
reshaped_arr = arr.reshape(3, 3)

In [68]:
reshaped_arr

array([[43, 65, 78],
       [23, 45, 64],
       [34, 24, 54]])

In [71]:
arr[arr> 50]

array([65, 78, 64, 54])

In [12]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr.dtype)

int64


In [14]:
arr.astype("float64")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [4]:
print(np.sum(arr, axis=0))

[12 15 18]


In [5]:
print(np.sum(arr, axis=1))

[ 6 15 24]


In [10]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


In [16]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])


print(arr3D[0, 1, 2]) 

print(arr3D[:, 0, :])  

6
[[1 2 3]
 [7 8 9]]


In [18]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 6, 9], dtype= "int32")


In [20]:
arr3.dtype

dtype('int32')

In [3]:
arr4 = np.array([1, 2, 3, 4, 5])

In [12]:
arr7 = np.array([1, 2, 3, 4, 5])
results = arr7 ** 2


print(results)

[ 1  4  9 16 25]


In [13]:
results + 10

array([11, 14, 19, 26, 35])

In [23]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr5 = np.array([1, 2, 3])

In [24]:
result = arr4 + arr5
result

array([[2, 4, 6],
       [5, 7, 9]])

In [18]:
result

array([[ 1,  4,  9],
       [16, 25, 36]])

In [19]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr5 = np.array([1, 2, 3])

In [21]:
result = arr4 + arr5
result

array([[2, 4, 6],
       [5, 7, 9]])

In [33]:
data = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 90, 75],
                [43, 54, 23]])

mean = data.mean(axis = 0)
std = data.std(axis = 0)

Normalized_data = (data - mean) / std

Normalized_data

array([[-1.44685858, -1.34893253, -0.79741055],
       [-0.03528923, -0.14093325,  0.60978454],
       [ 1.37628011,  1.46973246,  1.31338208],
       [ 0.1058677 ,  0.02013332, -1.12575607]])